# Generated by Django 3.2 on 2023-06-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0010_auto_20230609_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='avg_rating',
        ),
    ]
